# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort pytest
        if [ -f requirements/test.txt ]; then pip install -r requirements/test.txt; fi
    - name: Lint with black
      run: |
        black --diff --check **.py
    - name: Lint with isort
      run: |
        isort --profile black --diff --check-only **.py
    - name: Test with pytest
      run: |
        pytest tests/
